name: travel_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  # Utility
  flutter_svg: ^1.0.3
  kartal: ^2.3.1

  # States
  provider: ^6.0.2

  #Cache
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/png/

  fonts:
    - family: GTWalsheimPro
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/GTWalsheimPro-Medium.ttf
          weight: 500
